export const GET_DADOS_DASHBOARD = "GET_DADOS_DASHBOARD";
export const RETRIEVE_DASHBOARD = "RETRIEVE_DASHBOARD";
export const CREATE_DASHBOARD = "CREATE_DASHBOARD";
export const CREATE_GRAFICO = "CREATE_GRAFICO";
export const UPDATE_GRAFICO = "UPDATE_GRAFICO";